openai_api_key = "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"
admin_username = "admin"
admin_password = "admin"
