openai_api_key = "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"
admin_username = "admin"
admin_password = "admin"